version: '3.8'

services:
  mailforge-app:
    build: .
    # container_name: mailforge_app # Removido para evitar conflitos no Portainer
    ports:
      - "8097:3000" # Porta Única (Externa 8097 -> Interna 3000)
    networks:
      - mailforge_net
    volumes:
      # Volume para persistir o banco de dados (dados não somem ao reiniciar)
      - mailforge_data:/app/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/mailforge.db # Aponta o SQLite para a pasta do volume
    restart: unless-stopped

networks:
  mailforge_net:
    driver: bridge # Rede Interna para comunicação

volumes:
  mailforge_data:
    name: mailforge_data # Volumes gerenciados pelo Portainer
